compute-a-16-69.o2.rc.hms.harvard.edu
removed gaps!	 filt_gaps: 0.0010743141174316406 seconds
start,end:0,32
start,end:32,64
start,end:64,96
start,end:96,128
Process Process-1:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
Process Process-2:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:128,160
start,end:160,192
Process Process-3:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
Process Process-4:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
Process Process-5:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:192,224
start,end:224,256
Process Process-6:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:256,288
Process Process-7:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:288,320
Process Process-8:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:320,352
Process Process-9:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:352,384
start,end:384,416
Process Process-11:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
Process Process-10:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
Process Process-12:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:416,448
Process Process-13:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:448,480
start,end:480,512
Process Process-14:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:512,544
Process Process-15:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:544,576
Process Process-16:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:576,608
Process Process-17:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:608,640
Process Process-18:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:640,672
start,end:672,704
Process Process-19:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
Process Process-20:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:704,736
Process Process-21:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
Process Process-22:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
start,end:736,768
start,end:768,800
start,end:800,832
Process Process-23:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
Process Process-24:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
Process Process-25:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
Process Process-26:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 50, in f
    queue.put([map(lambda i : 1/(np.sum(rncol*np.sum(msa==msa[i],axis=1,dtype=np.uint16)>=0.8,dtype=np.uint32)),np.arange(start_ind,end_ind))])
NameError: name 'queue' is not defined
slurmstepd: error: *** JOB 48420335 ON compute-a-16-69 CANCELLED AT 2019-08-14T12:23:53 ***
