compute-a-16-163.o2.rc.hms.harvard.edu
removed gaps!	 filt_gaps: 0.000766754150390625 seconds
num cpus: 4
[612 408 204   0]
num_jobs:  4
[204 408 612 816]
------------------------new process------------
start,end:612,817
processes initialized!
process appended!
------------------------new process------------
start,end:408,408
processes initialized!
process appended!
------------------------new process------------
start,end:204,612
processes initialized!
process appended!
------------------------new process------------
start,end:0,816
processes initialized!
process appended!
4
process started! <Process(Process-1, started)> True
process started! <Process(Process-2, started)> True
process started! <Process(Process-3, started)> True
816
Process Process-2:
Traceback (most recent call last):
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/n/app/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "multithreading.py", line 51, in f
    print(vec[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0
611
815
slurmstepd: error: *** JOB 48432421 ON compute-a-16-163 CANCELLED AT 2019-08-14T16:01:54 ***
